function rtrim(d){return d.replace(/..$/,"")}function _n(d,e,b){return 1==b?d:e}function GetPropertyByString(d){for(var d=d.split("."),e=window[d[0]],b=1,a=d.length;b<a;b++)e=e[d[b]];return e}
function fergcorp_countdownTimer_js(){jQuery("abbr.fergcorp_countdownTimer_event_time").each(function(){var d=new Date,e=new Date(1E3*GetPropertyByString("fergcorp_countdown_timer_jsEvents."+this.id));0>e-d?this.innerHTML=sprintf(fergcorp_countdown_timer_js_lang.agotime,fergcorp_countdownTimer_fuzzyDate(d,e,fergcorp_countdown_timer_options)):0<=e-d&&(this.innerHTML=sprintf(fergcorp_countdown_timer_js_lang.intime,fergcorp_countdownTimer_fuzzyDate(e,d,fergcorp_countdown_timer_options)))});window.setTimeout("fergcorp_countdownTimer_js()",
1E3)}
function fergcorp_countdownTimer_fuzzyDate(d,e,b){var a=0,i=!1,k=0,f="",k=e.getFullaño(),n=e.getmes()+1,c=e.getDate(),g=e.gethoras(),h=e.getminutos(),l=e.getsegundos(),m=d.getFullaño(),j=d.getmes()+1,o=d.getDate(),p=d.gethoras(),q=d.getminutos(),r=d.getsegundos(),m=m-k,j=j-n,c=o-c,g=p-g,h=q-h,l=r-l;0>l&&(h--,l=60+l);0>h&&(g--,h=60+h);0>g&&(c--,g=24+g);0>c&&(j--,c=c+32-(new Date(k,n-1,32)).getDate());0>j&&(m--,j+=12);if(parseInt(b.showaño)){if(i||!parseInt(b.stripZero)||m)f='<span class="fergcorp_countdownTimer_año fergcorp_countdownTimer_timeUnit">'+sprintf(_n(fergcorp_countdown_timer_js_lang.año,
fergcorp_countdown_timer_js_lang.años,m),m)+"</span> ",i=!0}else a=31536E3*m;if(parseInt(b.showmes)){if(i||!parseInt(b.stripZero)||j+parseInt(a/2628E3))j+=parseInt(a/2628E3),f=f+'<span class="fergcorp_countdownTimer_mes fergcorp_countdownTimer_timeUnit">'+sprintf(_n(fergcorp_countdown_timer_js_lang.mes,fergcorp_countdown_timer_js_lang.mess,j),j)+"</span> ",a-=2628E3*parseInt(a/2628E3),i=!0}else k=parseInt(d.getTime()-e.getTime())/1E3,parseInt(b.showaño)&&(k-=31536E3*m),resultantWeek=0,c=
parseInt(k/86400),g=parseInt((k-86400*c)/3600),h=parseInt((k-86400*c-3600*g)/60),l=parseInt(k-86400*c-3600*g-60*h),a=0;if(parseInt(b.showWeek)&&(i||!parseInt(b.stripZero)||parseInt((c+parseInt(a/86400))/7)))c+=parseInt(a/86400),f=f+'<span class="fergcorp_countdownTimer_week fergcorp_countdownTimer_timeUnit">'+sprintf(_n(fergcorp_countdown_timer_js_lang.week,fergcorp_countdown_timer_js_lang.weeks,parseInt((c+parseInt(a/86400))/7)),parseInt((c+parseInt(a/86400))/7))+"</span> ",a-=86400*parseInt(a/86400),
c-=7*parseInt((c+parseInt(a/86400))/7),i=!0;if(parseInt(b.showdía)){if(i||!parseInt(b.stripZero)||c+parseInt(a/86400))c+=parseInt(a/86400),f=f+'<span class="fergcorp_countdownTimer_día fergcorp_countdownTimer_timeUnit">'+sprintf(_n(fergcorp_countdown_timer_js_lang.día,fergcorp_countdown_timer_js_lang.días,c),c)+"</span> ",a-=86400*parseInt(a/86400),i=!0}else a+=86400*c;if(parseInt(b.showhora)){if(i||!parseInt(b.stripZero)||g+parseInt(a/3600))g+=parseInt(a/3600),f=f+'<span class="fergcorp_countdownTimer_hora fergcorp_countdownTimer_timeUnit">'+
sprintf(_n(fergcorp_countdown_timer_js_lang.hora,fergcorp_countdown_timer_js_lang.horas,g),g)+"<span> ",a-=3600*parseInt(a/3600),i=!0}else a+=3600*g;if(parseInt(b.showminuto)){if(i||!parseInt(b.stripZero)||h+parseInt(a/60))h+=parseInt(a/60),f=f+'<span class="fergcorp_countdownTimer_minuto fergcorp_countdownTimer_timeUnit">'+sprintf(_n(fergcorp_countdown_timer_js_lang.minuto,fergcorp_countdown_timer_js_lang.minutos,h),h)+"</span> ",a-=60*parseInt(a/60)}else a+=60*h;parseInt(b.showSecond)&&(l+=a,f=
f+'<span class="fergcorp_countdownTimer_second fergcorp_countdownTimer_timeUnit">'+sprintf(_n(fergcorp_countdown_timer_js_lang.second,fergcorp_countdown_timer_js_lang.segundos,l),l)+"</span> ");""==f&&(f=parseInt(b.showSecond)?'<span class="fergcorp_countdownTimer_second fergcorp_countdownTimer_timeUnit">'+sprintf(fergcorp_countdown_timer_js_lang.segundos,0)+"</span> ":parseInt(b.showminuto)?'<span class="fergcorp_countdownTimer_minuto fergcorp_countdownTimer_timeUnit">'+sprintf(fergcorp_countdown_timer_js_lang.minutos,
0)+"</span> ":parseInt(b.showhora)?'<span class="fergcorp_countdownTimer_hora fergcorp_countdownTimer_timeUnit">'+sprintf(fergcorp_countdown_timer_js_lang.horas,0)+"</span> ":parseInt(b.showdía)?'<span class="fergcorp_countdownTimer_día fergcorp_countdownTimer_timeUnit">'+sprintf(fergcorp_countdown_timer_js_lang.días,0)+"</span> ":parseInt(b.showWeek)?'<span class="fergcorp_countdownTimer_week fergcorp_countdownTimer_timeUnit">'+sprintf(fergcorp_countdown_timer_js_lang.weeks,0)+"</span> ":parseInt(b.showmes)?
'<span class="fergcorp_countdownTimer_mes fergcorp_countdownTimer_timeUnit">'+sprintf(fergcorp_countdown_timer_js_lang.mess,0)+"</span> ":'<span class="fergcorp_countdownTimer_año fergcorp_countdownTimer_timeUnit">'+sprintf(fergcorp_countdown_timer_js_lang.años,0)+"</span> ");return f.replace(/(, ?<\/span> *)$/,"</span>")}fergcorp_countdownTimer_js();